return {
    "SmiteshP/nvim-navic",
    lazy = true,
    init = function()
        vim.g.navic_silence = true
    end,
    opts = {
        highlight = true,
        separator = "  ",
        depth_limit = 5,
        icons = {
            File = "",
            Module = "",
            Namespace = "",
            Package = "",
            Class = "",
            Method = "",
            Property = "",
            Field = "",
            Constructor = "",
            Enum = "",
            Interface = "",
            Function = "",
            Variable = "",
            Constant = "",
            String = "",
            Number = "",
            Boolean = "",
            Array = "",
            Object = "",
            Key = "",
            Null = "",
            EnumMember = "",
            Struct = "",
            Event = "",
            Operator = "",
            TypeParameter = "",
        },
    },
}
